services:

  selenium:
    image: selenium/standalone-chrome:latest
    #container_name: selenium_multi
    restart: always
    shm_size: 9g
    ports:
      - "4444:4444"
      - "5900:5900"
    environment:
      SE_NODE_MAX_SESSIONS: 10
      SE_NODE_OVERRIDE_MAX_SESSIONS: true # Mejora el rendimiento en sistemas con poca memoria compartida
    volumes:
      - ~/selenium:/temp
    networks:
      - api-network
      
  app:
    build: .
    restart: on-failure
    ports:
      - "5000:5000"  # Mapea el puerto 5000 del contenedor al puerto 5000 de la máquina local
    # environment:
    #   - SELENIUM_URL=http://selenium:4444/wd/hub  # URL para conectarse al contenedor de Selenium
    depends_on:
      - selenium  # Asegura que Selenium esté disponible antes de iniciar la aplicación
    networks:
      - api-network

networks:
  api-network:
    driver: bridge